"""empty message

Revision ID: 1038c35f5268
Revises: 783300aa8cbe
Create Date: 2018-08-19 17:05:33.022453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1038c35f5268'
down_revision = '783300aa8cbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Assignments_user_id_fkey', 'Assignments', type_='foreignkey')
    op.drop_column('Assignments', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Assignments', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Assignments_user_id_fkey', 'Assignments', 'Users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
