"""empty message

Revision ID: 20c264573b90
Revises: 1038c35f5268
Create Date: 2018-08-19 17:10:26.370927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c264573b90'
down_revision = '1038c35f5268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users_Assignments', sa.Column('assignment_id', sa.Integer(), nullable=False))
    op.add_column('Users_Assignments', sa.Column('userCompleted', sa.Boolean(), nullable=True))
    op.add_column('Users_Assignments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('Users_Assignments_StudentID_fkey', 'Users_Assignments', type_='foreignkey')
    op.drop_constraint('Users_Assignments_AssignmentID_fkey', 'Users_Assignments', type_='foreignkey')
    op.create_foreign_key(None, 'Users_Assignments', 'Assignments', ['assignment_id'], ['assignment_id'])
    op.create_foreign_key(None, 'Users_Assignments', 'Users', ['user_id'], ['user_id'])
    op.drop_column('Users_Assignments', 'AssignmentID')
    op.drop_column('Users_Assignments', 'StudentID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users_Assignments', sa.Column('StudentID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Users_Assignments', sa.Column('AssignmentID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Users_Assignments', type_='foreignkey')
    op.drop_constraint(None, 'Users_Assignments', type_='foreignkey')
    op.create_foreign_key('Users_Assignments_AssignmentID_fkey', 'Users_Assignments', 'Assignments', ['AssignmentID'], ['assignment_id'])
    op.create_foreign_key('Users_Assignments_StudentID_fkey', 'Users_Assignments', 'Users', ['StudentID'], ['user_id'])
    op.drop_column('Users_Assignments', 'user_id')
    op.drop_column('Users_Assignments', 'userCompleted')
    op.drop_column('Users_Assignments', 'assignment_id')
    # ### end Alembic commands ###
