"""empty message

Revision ID: 311e34abddd7
Revises: a5d9b6ef9430
Create Date: 2018-08-20 02:35:55.450032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311e34abddd7'
down_revision = 'a5d9b6ef9430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users_Assignments', sa.Column('Status', sa.Integer(), nullable=True))
    op.drop_column('Users_Assignments', 'UserCompleted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users_Assignments', sa.Column('UserCompleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('Users_Assignments', 'Status')
    # ### end Alembic commands ###
