"""empty message

Revision ID: 366445dbc118
Revises: 78103ad49216
Create Date: 2018-08-18 21:31:40.158326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366445dbc118'
down_revision = '78103ad49216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Disciplines', 'Type', new_column_name='isOnline')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Disciplines', 'isOnline', new_column_name='Type')
    # ### end Alembic commands ###
