"""empty message

Revision ID: 530d2211fc14
Revises: 
Create Date: 2018-08-18 20:44:30.017408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '530d2211fc14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Disciplines',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('DisciplineID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('DisciplineID')
    )
    op.drop_column('Assignments', 'Due_Date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Assignments', sa.Column('Due_Date', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('Disciplines')
    # ### end Alembic commands ###
