"""empty message

Revision ID: 78103ad49216
Revises: 0a4979bc296c
Create Date: 2018-08-18 21:20:17.310866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78103ad49216'
down_revision = '0a4979bc296c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Assignments', sa.Column('DisciplineID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Assignments', 'Disciplines', ['DisciplineID'], ['DisciplineID'])
    op.drop_column('Assignments', 'Discipline')
    op.add_column('Disciplines', sa.Column('Name', sa.String(length=60), nullable=True))
    op.add_column('Disciplines', sa.Column('Type', sa.Boolean(), nullable=True))
    op.drop_column('Disciplines', 'Nome')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Disciplines', sa.Column('Nome', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.drop_column('Disciplines', 'Type')
    op.drop_column('Disciplines', 'Name')
    op.add_column('Assignments', sa.Column('Discipline', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Assignments', type_='foreignkey')
    op.drop_column('Assignments', 'DisciplineID')
    # ### end Alembic commands ###
