"""empty message

Revision ID: 783300aa8cbe
Revises: 7aae6200c08b
Create Date: 2018-08-19 16:40:09.065873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783300aa8cbe'
down_revision = '7aae6200c08b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users_Assignments',
    sa.Column('StudentID', sa.Integer(), nullable=True),
    sa.Column('AssignmentID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['AssignmentID'], ['Assignments.assignment_id'], ),
    sa.ForeignKeyConstraint(['StudentID'], ['Users.user_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users_Assignments')
    # ### end Alembic commands ###
