"""empty message

Revision ID: 7aae6200c08b
Revises: c86f60bd0c79
Create Date: 2018-08-19 15:41:02.581171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aae6200c08b'
down_revision = 'c86f60bd0c79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Disciplines_user_id_fkey', 'Disciplines', type_='foreignkey')
    op.drop_column('Disciplines', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Disciplines', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Disciplines_user_id_fkey', 'Disciplines', 'Users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
