"""empty message

Revision ID: a5d9b6ef9430
Revises: cf67b202d764
Create Date: 2018-08-19 20:44:51.401416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5d9b6ef9430'
down_revision = 'cf67b202d764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Assignments_Codigo'), 'Assignments', ['Codigo'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Assignments_Codigo'), table_name='Assignments')
    # ### end Alembic commands ###
