"""empty message

Revision ID: c86f60bd0c79
Revises: 366445dbc118
Create Date: 2018-08-19 15:34:41.046568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c86f60bd0c79'
down_revision = '366445dbc118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users_Disciplines',
    sa.Column('StudentID', sa.Integer(), nullable=True),
    sa.Column('DisciplineID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['DisciplineID'], ['Disciplines.DisciplineID'], ),
    sa.ForeignKeyConstraint(['StudentID'], ['Users.user_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users_Disciplines')
    # ### end Alembic commands ###
