"""empty message

Revision ID: cf67b202d764
Revises: cff971611434
Create Date: 2018-08-19 20:32:45.628932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf67b202d764'
down_revision = 'cff971611434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Assignments', sa.Column('Codigo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Assignments', 'Codigo')
    # ### end Alembic commands ###
