"""empty message

Revision ID: cff971611434
Revises: f9bf16f16e95
Create Date: 2018-08-19 20:00:44.750686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff971611434'
down_revision = 'f9bf16f16e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users_Assignments', 'UserCompleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users_Assignments', 'UserCompleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
